services:
  - type: web
    name: medconnect-frontend
    buildCommand: npm run build
    publishDir: build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 